version: "3.0"

services:
  productservice:
    image: productservice
    container_name: productservice
    ports:
      - 5000:80
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  orderservice:
    image: orderservice
    container_name: orderservice
    ports:
      - 5001:80  
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'

  isignalrservice:
    image: isignalrservice
    container_name: isignalrservice
    ports:
      - 5002:80  
    environment:
      - 'CONSUL_ENABLED=false'
      - 'VAULT_ENABLED=false'


