apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3party.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: seq
  name: seq
spec:
  ports:
  - name: "5341"
    port: 5341
    targetPort: 80
  selector:
    io.kompose.service: seq
status:
  loadBalancer: {}
