kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30503
      name: web
    - protocol: TCP
      port: 8080
      nodePort: 30504
      name: admin
  type: NodePort